api_version: 1
runtime: python27
threadsafe: true

libraries:
- name: jinja2
  version: 2.6
- name: webapp2
  version: latest

handlers:
- url: /_api/.*
  script: app.main.api_app
  secure: always
- url: /.*
  script: app.main.app
